{% set version = "1.8.3" %}

package:
  name: wgrib
  version: {{ version }}

source:
  fn: wgrib.tar
  url: https://ftp.cpc.ncep.noaa.gov/wd51we/wgrib/wgrib.tar.v{{ version }}
  sha256: 94db09752e23c803c79f066bfe1dfef6a94c6a4d95dba9d634fc276f6793ed0c
  patches:
    - ccompiler.patch

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make  # [not win]
    - m2-make  # [win]
  host:

test:
  files:
    - land.grb
  commands:
    - wgrib land.grb -d 1

about:
  home: https://www.cpc.ncep.noaa.gov/products/wesley/wgrib.html
  license: Public Domain
  license_file: NOTICE
  summary: Manipulate, inventory and decode GRIB files

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
