{% set version = "1.8.2" %}

package:
  name: wgrib
  version: {{ version }}

source:
  fn: wgrib.tar
  url: https://ftp.cpc.ncep.noaa.gov/wd51we/wgrib/wgrib.tar.v{{ version }}
  sha256: fe44679f944321024e53b04798845f0b7ba3571399f846a50a1f8544684b6d7a
  patches:
    - ccompiler.patch

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make  # [not win]
    - m2-make  # [win]
  host:

test:
  files:
    - land.grb
  commands:
    - wgrib land.grb -d 1

about:
  home: https://www.cpc.ncep.noaa.gov/products/wesley/wgrib.html
  license: Public Domain
  license_file: NOTICE
  summary: 'Manipulate, inventory and decode GRIB files'

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
