travis:
  secure:
    BINSTAR_TOKEN: rZJqnKAb7Nz0eyMpIbfV5bbnpAOIZDXiUQzYuiB8dlcoVgNYHE5ekKUvGNbVODYbzpMaUi4I8Z5GwjoeuVw5vDrAS5w1mvy2V5JqV0dWhPw2OCOSdu1hhl621NgWm8EOPS4MDVc7tHosHUcoQuaHUwkU8NGNOmAI41fCp5BZM3VZqAFneM+5/QYv4Jv5Z2YmP3ZT+8PZNwPJWURmg7UL0vzUFXnNXbyLSbtHveY+wr05OF1DS/q+rbrpSBxUHDTSfz5yXGFsltt9cfrHswQwEldwrP64VxmtnqamRkg2Nb+YH0WaWj25Ejs7/+frpp+r4u0bRmiY7Ur/uF+1iT40jlNSwzV1oSfT4TxzJfs5IHyklZjna9c/DyfLVXexNpmDp+qUf1gomZX7wC3xzQ2opdW4Rg40wOEk0Qhg7xU51ZquEooZuocAVk76yrlbzSo1fE9bMC+U79RsuKkcsY/aqU6uZSt0Jz4TF63GCiPs75XdagerWu/lf6C5qvgt6A4iz4bhgbbO6FO9Vk94tsvv15XEKmc0Q8PaJQd03nd10oysbUoy2qhVedTQfcPDOnIGZ71B2iOB9s+rgV5c9QdoxXpO0ahKvjtUJQoDgCmKJ6M+xioLD19R7Y/iNhfWq4E7QMrZmE4EPrbAsz3gOP7i8mFFItAzG7k0BVRIcpq5ctM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
